#!/bin/bash

# zsh font and theme
  sudo apt-get install powerline fonts-powerline
  sudo apt-get install zsh-theme-powerlevel9k
  echo "source /usr/share/powerlevel9k/powerlevel9k.zsh-theme" >> ~/.zshrc
  sudo apt-get install zsh-syntax-highlighting
  echo "source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> ~/.zshrc

# modifications
cat >> ~/.zshrc << EOL
  #remove excess stuff from zshbash
  POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs)
  POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
  POWERLEVEL9K_DISABLE_RPROMPT=true
  
  # NVM 
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
    
#docker aliases
alias start-redis="docker container exec -it redis /bin/bash"

#My custom aliases
gs () {git rebase -i $(git merge-base origin/develop $(git branch | grep \* | cut -d ' ' -f2))}
gp () {git push origin $(git branch | grep \* | cut -d ' ' -f2)}
alias gc="git checkout"
alias gcb="git checkout -b"
alias gb="git branch"
alias gr="git fetch origin && git rebase origin/develop"
alias gcp="git cherry-pick"
gac () {
git add .
read commit_message
git commit -m $commit_message
gp
}


alias vpnup="wg-quick up wg0"
alias vpndown="wg-quick down wg0"
alias localhost="google-chrome "http://localhost:3000" </dev/null &>/dev/null &"

alias stop="cd ~/repos/platforms && docker-compose down && vpndown"

start() {
if [ $1 = '-l' ]
then
cd ~/repos/platforms && docker-compose up -d && vpnup && code ./ && npm run dev
else
cd ~/repos/platforms && vpnup && code ./ && npm run dev:cloud
fi
}
EOL
