#!/bin/bash

# zsh font and theme
sudo apt-get install powerline fonts-powerline
sudo apt-get install zsh-theme-powerlevel9k
echo "source /usr/share/powerlevel9k/powerlevel9k.zsh-theme" >> ~/.zshrc
sudo apt-get install zsh-syntax-highlighting
echo "source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> ~/.zshrc

# add git aliases to zsh
cat >> ~/.zshrc << EOL
gs () {git rebase -i $(git merge-base origin/develop $(git branch | grep \* | cut -d ' ' -f2))}
gp () {git push origin $(git branch | grep \* | cut -d ' ' -f2)}
alias fj="cd ~/repos/sales-ext"
alias gc="git checkout"
alias gcb="git checkout -b"
alias gb="git branch"
alias gr="git fetch origin && git rebase origin/develop"
alias gcp="git cherry-pick"
gac () {
git add .
read commit_message
git commit -m $commit_message
gp
}
EOL
